[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "necro"
version = "0.0.0"
description = "The fastest Python web framework."
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Dzara Melcone" }]

[project.scripts]
necro = "necro.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["python/necro"]

[tool.hatch.build.targets.wheel.hooks.custom]
path = "hatch.py"
